using Random: seed!, randn
using StableRNGs

# Generate the exact heatmap parameter fixtures used by UnicodePlots.jl tests.
# UnicodePlots.jl uses StableRNG(1_337) as its test RNG (see test/runtests.jl).
# Each matrix is generated by re-seeding that RNG with 1_337 before calling randn.
function write_matrix_json(io::IO, m::Matrix{Float64}, indent::String = "  ")
    println(io, "[")
    for i in 1:size(m, 1)
        print(io, indent * "  [")
        for j in 1:size(m, 2)
            j > 1 && print(io, ", ")
            print(io, repr(m[i, j]))
        end
        print(io, "]")
        i < size(m, 1) ? println(io, ",") : println(io)
    end
    print(io, indent * "]")
end

function main()
    rng = StableRNG(1_337)

    dims = [
        (60, 60),
        (10, 10),
        (10, 11),
        (1, 1),
        (1, 2),
        (2, 1),
        (10, 15),
        (15, 10),
        (20, 200),
        (200, 20),
    ]

    mats = Dict{String, Matrix{Float64}}()
    for (m, n) in dims
        seed!(rng, 1_337)
        mats["$(m)x$(n)"] = randn(rng, m, n)
    end

    out_path = joinpath(@__DIR__, "julia_heatmap_data.json")
    open(out_path, "w") do io
        println(io, "{")
        println(io, "  \"generated_by\": \"spec/fixtures/generate_julia_heatmap_data.jl\",")
        println(io, "  \"seed\": 1337,")
        for (idx, (m, n)) in enumerate(dims)
            key = "$(m)x$(n)"
            print(io, "  \"$(key)\": ")
            write_matrix_json(io, mats[key])
            idx < length(dims) ? println(io, ",") : println(io)
        end
        println(io, "}")
    end

    println("wrote ", out_path)
end

main()
