using Random: seed!, randn
using StableRNGs

# Generate the exact heatmap parameter fixtures used by UnicodePlots.jl tests.
# UnicodePlots.jl uses StableRNG(1_337) as its test RNG (see test/runtests.jl).
# Each matrix is generated by re-seeding that RNG with 1_337 before calling randn.
function write_matrix_json(io::IO, m::Matrix{Float64}, indent::String = "  ")
    println(io, "[")
    for i in 1:size(m, 1)
        print(io, indent * "  [")
        for j in 1:size(m, 2)
            j > 1 && print(io, ", ")
            print(io, repr(m[i, j]))
        end
        print(io, "]")
        i < size(m, 1) ? println(io, ",") : println(io)
    end
    print(io, indent * "]")
end

function main()
    rng = StableRNG(1_337)

    seed!(rng, 1_337)
    x60 = randn(rng, 60, 60)

    seed!(rng, 1_337)
    x10 = randn(rng, 10, 10)

    seed!(rng, 1_337)
    x11 = randn(rng, 10, 11)

    out_path = joinpath(@__DIR__, "julia_heatmap_data.json")
    open(out_path, "w") do io
        println(io, "{")
        println(io, "  \"generated_by\": \"spec/fixtures/generate_julia_heatmap_data.jl\",")
        println(io, "  \"seed\": 1337,")
        print(io, "  \"60x60\": ")
        write_matrix_json(io, x60)
        println(io, ",")
        print(io, "  \"10x10\": ")
        write_matrix_json(io, x10)
        println(io, ",")
        print(io, "  \"10x11\": ")
        write_matrix_json(io, x11)
        println(io)
        println(io, "}")
    end

    println("wrote ", out_path)
end

main()
