require "../spec_helper"
require "json"

# Heatmap parameter cases use deterministic input values generated by Julia.
# Keeping these fixtures under spec/ avoids mixing test data into library source.
REFERENCE_FIXTURE_DIR = File.join(__DIR__, "..", "fixtures")

HEATMAP_FIXTURE_PATH  = File.join(REFERENCE_FIXTURE_DIR, "julia_heatmap_data.json")
HEATMAP_FIXTURE_JSON  = JSON.parse(File.read(HEATMAP_FIXTURE_PATH))
HEATMAP_FIXTURE_CACHE = {} of String => Array(Array(Float64))

DENSITYPLOT_FIXTURE_PATH = File.join(REFERENCE_FIXTURE_DIR, "julia_densityplot_data.json")
DENSITYPLOT_FIXTURE_JSON = JSON.parse(File.read(DENSITYPLOT_FIXTURE_PATH))
DENSITYPLOT_X            = DENSITYPLOT_FIXTURE_JSON["x"].as_a.map(&.as_f)
DENSITYPLOT_Y            = DENSITYPLOT_FIXTURE_JSON["y"].as_a.map(&.as_f)

# Spy fixtures generated by spec/fixtures/generate_julia_spy_data.jl
SPY_FIXTURE_PATH = File.join(REFERENCE_FIXTURE_DIR, "julia_spy_data.json")
SPY_FIXTURE_JSON = JSON.parse(File.read(SPY_FIXTURE_PATH))

POLARPLOT_FIXTURE_PATH = File.join(REFERENCE_FIXTURE_DIR, "julia_polarplot_data.json")
POLARPLOT_FIXTURE_JSON = JSON.parse(File.read(POLARPLOT_FIXTURE_PATH))

# Returns a matrix fixture by key ("60x60", "10x10", "10x11").
# The parsed matrix is cached because multiple examples reuse the same payload.
def heatmap_fixture_matrix(key : String) : Array(Array(Float64))
  if matrix = HEATMAP_FIXTURE_CACHE[key]?
    return matrix
  end

  rows = HEATMAP_FIXTURE_JSON[key].as_a
  matrix = rows.map { |row| row.as_a.map(&.as_f) }
  HEATMAP_FIXTURE_CACHE[key] = matrix
  matrix
end

def densityplot_fixture_xprime(x : Array(Float64)) : Array(Float64)
  xprime = x.dup
  lo = (0.1 * x.size).round.to_i
  hi = (0.6 * x.size).round.to_i
  val = 0.5 * x.max
  (lo - 1..hi - 1).each do |idx|
    xprime[idx] = val
  end
  xprime
end

def matrix_columns(rows : Array(Array(Float64))) : Array(Array(Float64))
  return [] of Array(Float64) if rows.empty?
  ncols = rows.first.size
  Array.new(ncols) do |col_idx|
    rows.map { |row| row[col_idx] }
  end
end

# Reconstruct a dense matrix from the spy fixture JSON entry (sparse COO format, 1-indexed).
def spy_fixture_matrix(key : String) : Array(Array(Float64))
  entry = SPY_FIXTURE_JSON[key]
  nrows = entry["nrows"].as_i
  ncols = entry["ncols"].as_i
  rows_a = entry["rows"].as_a.map(&.as_i)
  cols_a = entry["cols"].as_a.map(&.as_i)
  vals_a = entry["vals"].as_a.map(&.as_f)
  matrix = Array.new(nrows) { Array.new(ncols, 0.0) }
  rows_a.each_with_index do |row, idx|
    matrix[row - 1][cols_a[idx] - 1] = vals_a[idx]
  end
  matrix
end

# Deterministic sparse matrix matching Julia's flip test:
#   I = [1,4,3,5], J = [4,7,18,9], V = [1,2,-5,3]
def spy_flip_matrix : Array(Array(Float64))
  a = Array.new(5) { Array.new(18, 0.0) }
  a[0][3] = 1.0
  a[3][6] = 2.0
  a[2][17] = -5.0
  a[4][8] = 3.0
  a
end

def polarplot_fixture_linspace(case_key : String, axis : String) : Array(Float64)
  entry = POLARPLOT_FIXTURE_JSON[case_key][axis]
  start_v = entry["start"].as_f
  stop_v = entry["stop"].as_f
  length = entry["length"].as_i
  linspace(start_v, stop_v, length)
end

def linspace(start_v : Float64, end_v : Float64, length : Int32) : Array(Float64)
  return [] of Float64 if length <= 0
  return [start_v] if length == 1
  span = end_v - start_v
  denom = (length - 1).to_f64
  Array.new(length) { |i| start_v + span * i.to_f64 / denom }
end

def range_by_step(start_v : Float64, stop_v : Float64, step_v : Float64) : Array(Float64)
  raise ArgumentError.new("step must be positive") if step_v <= 0.0
  count = ((stop_v - start_v) / step_v).round.to_i32 + 1
  Array.new(count) { |i| start_v + step_v * i.to_f64 }
end

def gaussian_2d(
  x : Array(Float64) = range_by_step(-3.0, 3.0, 0.01),
  y : Array(Float64) = range_by_step(-7.0, 3.0, 0.01),
  x0 : Float64 = 0.0,
  y0 : Float64 = -2.0,
  sigma_x : Float64 = 1.0,
  sigma_y : Float64 = 2.0,
) : {Array(Float64), Array(Float64), Array(Array(Float64))}
  z = y.map do |y_value|
    x.map do |x_value|
      xterm = ((x_value - x0) / (2.0 * sigma_x))**2
      yterm = ((y_value - y0) / (2.0 * sigma_y))**2
      Math.exp(-xterm - yterm)
    end
  end
  {x, y, z}
end

def known_dates2_braille_jitter?(expected : String, actual : String) : Bool
  expected_chars = expected.chars
  actual_chars = actual.chars
  return false unless expected_chars.size == actual_chars.size

  diffs = 0
  expected_chars.each_with_index do |exp_char, i|
    act_char = actual_chars[i]
    next if exp_char == act_char

    allowed =
      (exp_char == '⠦' && act_char == '⢦') ||
        (exp_char == '⡤' && act_char == '⢤') ||
        (exp_char == '⠘' && act_char == '⠈') ||
        (exp_char == '⠵' && act_char == '⢵')
    return false unless allowed
    diffs += 1
  end

  diffs <= 2
end
