require "./spec_helper"
require "json"

# Heatmap parameter cases use deterministic input values generated by Julia.
# Keeping these fixtures under spec/ avoids mixing test data into library source.
HEATMAP_FIXTURE_PATH  = File.join(__DIR__, "fixtures", "julia_heatmap_data.json")
HEATMAP_FIXTURE_JSON  = JSON.parse(File.read(HEATMAP_FIXTURE_PATH))
HEATMAP_FIXTURE_CACHE = {} of String => Array(Array(Float64))

DENSITYPLOT_FIXTURE_PATH = File.join(__DIR__, "fixtures", "julia_densityplot_data.json")
DENSITYPLOT_FIXTURE_JSON = JSON.parse(File.read(DENSITYPLOT_FIXTURE_PATH))
DENSITYPLOT_X            = DENSITYPLOT_FIXTURE_JSON["x"].as_a.map(&.as_f)
DENSITYPLOT_Y            = DENSITYPLOT_FIXTURE_JSON["y"].as_a.map(&.as_f)

# Returns a matrix fixture by key ("60x60", "10x10", "10x11").
# The parsed matrix is cached because multiple examples reuse the same payload.
def heatmap_fixture_matrix(key : String) : Array(Array(Float64))
  if matrix = HEATMAP_FIXTURE_CACHE[key]?
    return matrix
  end

  rows = HEATMAP_FIXTURE_JSON[key].as_a
  matrix = rows.map { |row| row.as_a.map(&.as_f) }
  HEATMAP_FIXTURE_CACHE[key] = matrix
  matrix
end

def densityplot_fixture_xprime(x : Array(Float64)) : Array(Float64)
  xprime = x.dup
  lo = (0.1 * x.size).round.to_i
  hi = (0.6 * x.size).round.to_i
  val = 0.5 * x.max
  (lo - 1..hi - 1).each do |idx|
    xprime[idx] = val
  end
  xprime
end

describe "Julia reference output compatibility" do
  x = [-1.0, 1.0, 3.0, 3.0, -1.0]
  y = [2.0, 0.0, -5.0, 2.0, -5.0]

  describe "lineplot" do
    it "matches lineplot/default" do
      p = UnicodePlot.lineplot(x, y)
      test_ref("lineplot/default.txt", p)
    end

    it "matches lineplot/y_only" do
      p = UnicodePlot.lineplot([2.0, 0.0, -5.0, 2.0, -5.0])
      test_ref("lineplot/y_only.txt", p)
    end

    it "matches lineplot/range1" do
      p = UnicodePlot.lineplot((6..10).map(&.to_f).to_a)
      test_ref("lineplot/range1.txt", p)
    end

    it "matches lineplot/range2" do
      p = UnicodePlot.lineplot((11..15).map(&.to_f).to_a, (6..10).map(&.to_f).to_a)
      test_ref("lineplot/range2.txt", p)
    end

    it "matches lineplot/scale1" do
      p = UnicodePlot.lineplot(x.map { |v| v * 1e3 + 15 }, y.map { |v| v * 1e-3 - 15 })
      test_ref("lineplot/scale1.txt", p)
    end

    it "matches lineplot/scale2" do
      p = UnicodePlot.lineplot(x.map { |v| v * 1e-3 + 15 }, y.map { |v| v * 1e3 - 15 })
      test_ref("lineplot/scale2.txt", p)
    end

    it "matches lineplot/scale3" do
      p = UnicodePlot.lineplot([-1.0, 2.0, 3.0, 700_000.0], [1.0, 2.0, 9.0, 4_000_000.0])
      test_ref("lineplot/scale3.txt", p)
    end

    it "matches lineplot/scale3_small" do
      p = UnicodePlot.lineplot([-1.0, 2.0, 3.0, 700_000.0], [1.0, 2.0, 9.0, 4_000_000.0], height: 5, width: 18)
      test_ref("lineplot/scale3_small.txt", p)
    end

    it "matches lineplot/limits" do
      p = UnicodePlot.lineplot(x, y, xlim: {-1.5, 3.5}, ylim: {-5.5, 2.5})
      test_ref("lineplot/limits.txt", p)
    end

    it "matches lineplot/nogrid" do
      p = UnicodePlot.lineplot(x, y, grid: false)
      test_ref("lineplot/nogrid.txt", p)
    end

    it "matches lineplot/blue (ANSI stripped)" do
      p = UnicodePlot.lineplot(x, y, name: "points1")
      test_ref("lineplot/blue.txt", p)
    end

    it "matches lineplot/parameters1" do
      p = UnicodePlot.lineplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      test_ref("lineplot/parameters1.txt", p)
    end

    it "matches lineplot/parameters2" do
      p = UnicodePlot.lineplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.lineplot!(p, [0.5, 1.0, 1.5], name: "points2")
      test_ref("lineplot/parameters2.txt", p)
    end

    it "matches lineplot/parameters3" do
      p = UnicodePlot.lineplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.lineplot!(p, [0.5, 1.0, 1.5], name: "points2")
      UnicodePlot.lineplot!(p, [-0.5, 0.5, 1.5], [0.5, 1.0, 1.5], name: "points3")
      test_ref("lineplot/parameters3.txt", p)
    end

    it "matches lineplot/nocolor" do
      p = UnicodePlot.lineplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.lineplot!(p, [0.5, 1.0, 1.5], name: "points2")
      UnicodePlot.lineplot!(p, [-0.5, 0.5, 1.5], [0.5, 1.0, 1.5], name: "points3")
      test_ref("lineplot/nocolor.txt", p)
    end

    it "matches lineplot/canvassize" do
      p = UnicodePlot.lineplot(x, y, title: "Scatter", canvas: :dot, height: 5, width: 10)
      test_ref("lineplot/canvassize.txt", p)
    end

    it "matches lineplot/sin" do
      p = UnicodePlot.lineplot(->(v : Float64) { Math.sin(v) }, name: "sin(x)", ylabel: "f(x)", xlabel: "x")
      test_ref("lineplot/sin.txt", p)
    end

    it "matches lineplot/sincos" do
      p = UnicodePlot.lineplot(->(v : Float64) { Math.sin(v) }, name: "sin(x)", ylabel: "f(x)", xlabel: "x")
      UnicodePlot.lineplot!(p, ->(v : Float64) { Math.cos(v) }, name: "cos(x)")
      test_ref("lineplot/sincos.txt", p)
    end

    it "matches lineplot/sin2" do
      p = UnicodePlot.lineplot(-0.5_f64, 6.0_f64, ->(v : Float64) { Math.sin(v) }, name: "sin(x)", ylabel: "f(x)", xlabel: "x")
      test_ref("lineplot/sin2.txt", p)
    end

    it "matches lineplot/sincos2" do
      p = UnicodePlot.lineplot(-0.5_f64, 6.0_f64, ->(v : Float64) { Math.sin(v) }, name: "sin(x)", ylabel: "f(x)", xlabel: "x")
      UnicodePlot.lineplot!(p, ->(v : Float64) { Math.cos(v) }, name: "cos(x)")
      test_ref("lineplot/sincos2.txt", p)
    end

    it "matches lineplot/sincostan2" do
      p = UnicodePlot.lineplot(-0.5_f64, 6.0_f64, ->(v : Float64) { Math.sin(v) }, name: "sin(x)", ylabel: "f(x)", xlabel: "x")
      UnicodePlot.lineplot!(p, ->(v : Float64) { Math.cos(v) }, name: "cos(x)")
      UnicodePlot.lineplot!(p, 2.5_f64, 3.5_f64, ->(v : Float64) { Math.tan(v) }, name: "tan(x)")
      test_ref("lineplot/sincostan2.txt", p)
    end

    it "matches lineplot/hvline" do
      p = UnicodePlot.lineplot([Float64::NAN], [Float64::NAN], xlim: {0.0, 8.0}, ylim: {0.0, 8.0})
      UnicodePlot.vline!(p, 2.0, [2.0, 6.0], color: :red)
      UnicodePlot.vline!(p, 6.0, [2.0, 6.0], color: :red)
      UnicodePlot.hline!(p, 2.0, [2.0, 6.0], color: :white)
      UnicodePlot.hline!(p, 6.0, [2.0, 6.0], color: :white)
      UnicodePlot.hline!(p, 7.0)
      UnicodePlot.vline!(p, 1.0)
      test_ref("lineplot/hvline.txt", p)
    end
  end

  describe "stairs" do
    sx = [1.0, 2.0, 4.0, 7.0, 8.0]
    sy = [1.0, 3.0, 4.0, 2.0, 7.0]

    it "matches lineplot/stairs_post (default style)" do
      p = UnicodePlot.stairs(sx, sy)
      test_ref("lineplot/stairs_post.txt", p)
    end

    it "matches lineplot/stairs_pre" do
      p = UnicodePlot.stairs(sx, sy, style: :pre)
      test_ref("lineplot/stairs_pre.txt", p)
    end

    it "matches lineplot/stairs_parameters" do
      p = UnicodePlot.stairs(sx, sy, title: "Foo", color: :red, xlabel: "x", name: "1")
      UnicodePlot.stairs!(p, sx.map { |v| v - 0.2 }, sy.map { |v| v + 1.5 }, name: "2")
      test_ref("lineplot/stairs_parameters.txt", p)
    end

    it "matches lineplot/stairs_parameters2" do
      p = UnicodePlot.stairs(sx, sy, title: "Foo", color: :red, xlabel: "x", name: "1")
      UnicodePlot.stairs!(p, sx.map { |v| v - 0.2 }, sy.map { |v| v + 1.5 }, name: "2")
      UnicodePlot.stairs!(p, sx, sy, name: "3", style: :pre)
      test_ref("lineplot/stairs_parameters2.txt", p)
    end

    it "matches lineplot/stairs_parameters2_nocolor" do
      p = UnicodePlot.stairs(sx, sy, title: "Foo", color: :red, xlabel: "x", name: "1")
      UnicodePlot.stairs!(p, sx.map { |v| v - 0.2 }, sy.map { |v| v + 1.5 }, name: "2")
      UnicodePlot.stairs!(p, sx, sy, name: "3", style: :pre)
      test_ref("lineplot/stairs_parameters2_nocolor.txt", p)
    end

    it "matches lineplot/stairs_edgecase" do
      p = UnicodePlot.stairs([1.0, 2.0, 4.0, 7.0, 8.0], [1.0, 3.0, 4.0, 2.0, 7_000.0])
      test_ref("lineplot/stairs_edgecase.txt", p)
    end
  end

  describe "scatterplot" do
    it "matches scatterplot/default" do
      p = UnicodePlot.scatterplot(x, y)
      test_ref("scatterplot/default.txt", p)
    end

    it "matches scatterplot/y_only (1-based x-axis)" do
      p = UnicodePlot.scatterplot([2.0, 0.0, -5.0, 2.0, -5.0])
      test_ref("scatterplot/y_only.txt", p)
    end

    it "matches scatterplot/range1" do
      p = UnicodePlot.scatterplot((6..10).map(&.to_f).to_a)
      test_ref("scatterplot/range1.txt", p)
    end

    it "matches scatterplot/range2" do
      p = UnicodePlot.scatterplot((11..15).map(&.to_f).to_a, (6..10).map(&.to_f).to_a)
      test_ref("scatterplot/range2.txt", p)
    end

    it "matches scatterplot/scale1" do
      p = UnicodePlot.scatterplot(x.map { |v| v * 1e3 + 15 }, y.map { |v| v * 1e-3 - 15 })
      test_ref("scatterplot/scale1.txt", p)
    end

    it "matches scatterplot/scale2" do
      p = UnicodePlot.scatterplot(x.map { |v| v * 1e-3 + 15 }, y.map { |v| v * 1e3 - 15 })
      test_ref("scatterplot/scale2.txt", p)
    end

    it "matches scatterplot/limits" do
      p = UnicodePlot.scatterplot(x, y, xlim: {-1.5, 3.5}, ylim: {-5.5, 2.5})
      test_ref("scatterplot/limits.txt", p)
    end

    it "matches scatterplot/nogrid" do
      p = UnicodePlot.scatterplot(x, y, grid: false)
      test_ref("scatterplot/nogrid.txt", p)
    end

    it "matches scatterplot/blue" do
      p = UnicodePlot.scatterplot(x, y, color: :blue, name: "points1")
      test_ref("scatterplot/blue.txt", p)
    end

    it "matches scatterplot/parameters1" do
      p = UnicodePlot.scatterplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      test_ref("scatterplot/parameters1.txt", p)
    end

    it "matches scatterplot/parameters2" do
      p = UnicodePlot.scatterplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.scatterplot!(p, [0.5, 1.0, 1.5], name: "points2")
      test_ref("scatterplot/parameters2.txt", p)
    end

    it "matches scatterplot/parameters3" do
      p = UnicodePlot.scatterplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.scatterplot!(p, [0.5, 1.0, 1.5], name: "points2")
      UnicodePlot.scatterplot!(p, [-0.5, 0.5, 1.5], [0.5, 1.0, 1.5], name: "points3")
      test_ref("scatterplot/parameters3.txt", p)
    end

    it "matches scatterplot/nocolor" do
      p = UnicodePlot.scatterplot(x, y, name: "points1", title: "Scatter", xlabel: "x", ylabel: "y")
      UnicodePlot.scatterplot!(p, [0.5, 1.0, 1.5], name: "points2")
      UnicodePlot.scatterplot!(p, [-0.5, 0.5, 1.5], [0.5, 1.0, 1.5], name: "points3")
      test_ref("scatterplot/nocolor.txt", p)
    end

    it "matches scatterplot/canvassize" do
      p = UnicodePlot.scatterplot(x, y, title: "Scatter", canvas: :dot, height: 5, width: 10)
      test_ref("scatterplot/canvassize.txt", p)
    end
  end

  describe "barplot" do
    it "matches barplot/default" do
      p = UnicodePlot.barplot(["bar", "foo"], [23.0, 37.0])
      test_ref("barplot/default.txt", p)
    end

    it "matches barplot/default2 (with barplot! appended)" do
      p = UnicodePlot.barplot(["bar", "foo"], [23.0, 37.0])
      UnicodePlot.barplot!(p, ["zoom"], [90.0])
      test_ref("barplot/default2.txt", p)
    end

    it "matches barplot/nocolor" do
      p = UnicodePlot.barplot(["bar", "foo"], [23.0, 37.0])
      test_ref("barplot/nocolor.txt", p)
    end

    it "matches barplot/ranges" do
      p = UnicodePlot.barplot(["2", "3", "4", "5", "6"], [11.0, 12.0, 13.0, 14.0, 15.0])
      test_ref("barplot/ranges.txt", p)
    end

    it "matches barplot/ranges2" do
      p = UnicodePlot.barplot(["2", "3", "4", "5", "6"], [11.0, 12.0, 13.0, 14.0, 15.0])
      UnicodePlot.barplot!(p, ["9", "10"], [20.0, 21.0])
      test_ref("barplot/ranges2.txt", p)
    end

    it "matches barplot/parameters1" do
      p = UnicodePlot.barplot(
        ["Paris", "New York", "Moskau", "Madrid"],
        [2.244, 8.406, 11.92, 3.165],
        title: "Relative sizes of cities",
        xlabel: "population [in mil]",
        color: :blue,
        margin: 7,
        padding: 3,
      )
      test_ref("barplot/parameters1.txt", p)
    end

    it "matches barplot/parameters1_nolabels" do
      p = UnicodePlot.barplot(
        ["Paris", "New York", "Moskau", "Madrid"],
        [2.244, 8.406, 11.92, 3.165],
        title: "Relative sizes of cities",
        xlabel: "population [in mil]",
        color: :blue,
        margin: 7,
        padding: 3,
        labels: false,
      )
      test_ref("barplot/parameters1_nolabels.txt", p)
    end

    it "matches barplot/parameters2" do
      p = UnicodePlot.barplot(
        ["Paris", "New York", "Moskau", "Madrid"],
        [2.244, 8.406, 11.92, 3.165],
        title: "Relative sizes of cities",
        xlabel: "population [in mil]",
        color: :yellow,
        border: :solid,
        symbols: ['='],
        width: 60,
      )
      test_ref("barplot/parameters2.txt", p)
    end

    it "matches barplot/edgecase_zeros" do
      p = UnicodePlot.barplot(["5", "4", "3", "2", "1"], [0.0, 0.0, 0.0, 0.0, 0.0])
      test_ref("barplot/edgecase_zeros.txt", p)
    end

    it "matches barplot/edgecase_onelarge" do
      p = UnicodePlot.barplot(["a", "b", "c", "d"], [1.0, 1.0, 1.0, 1_000_000.0])
      test_ref("barplot/edgecase_onelarge.txt", p)
    end

    it "matches barplot/col1 (8-bit terminal color, ANSI stripped)" do
      p = UnicodePlot.barplot(["B", "A"], [2.0, 1.0], color: 9_i32)
      test_ref("barplot/col1.txt", p)
    end
  end

  describe "histogram" do
    it "matches histogram/vert2 (deterministic vertical histogram)" do
      n = 30
      dat = [] of Float64
      (1..n).each { |i| i.times { dat << i.to_f } }
      p = UnicodePlot.histogram(dat, vertical: true, nbins: n)
      test_ref("histogram/vert2.txt", p)
    end

    it "matches histogram/float32" do
      p = UnicodePlot.histogram([0.1_f32, 0.1_f32, 0.0_f32])
      test_ref("histogram/float32.txt", p)
    end
  end

  describe "boxplot" do
    it "matches boxplot/default" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0])
      test_ref("boxplot/default.txt", p)
    end

    it "matches boxplot/default_name" do
      p = UnicodePlot.boxplot("series1", [1.0, 2.0, 3.0, 4.0, 5.0])
      test_ref("boxplot/default_name.txt", p)
    end

    it "matches boxplot/scale1 (xlim 0..5)" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0], xlim: {0.0, 5.0})
      test_ref("boxplot/scale1.txt", p)
    end

    it "matches boxplot/scale2 (xlim 0..6)" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0], xlim: {0.0, 6.0})
      test_ref("boxplot/scale2.txt", p)
    end

    it "matches boxplot/scale3 (xlim 0..10)" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0], xlim: {0.0, 10.0})
      test_ref("boxplot/scale3.txt", p)
    end

    it "matches boxplot/scale4 (xlim 0..20)" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0], xlim: {0.0, 20.0})
      test_ref("boxplot/scale4.txt", p)
    end

    it "matches boxplot/scale5 (xlim 0..40)" do
      p = UnicodePlot.boxplot([1.0, 2.0, 3.0, 4.0, 5.0], xlim: {0.0, 40.0})
      test_ref("boxplot/scale5.txt", p)
    end

    it "matches boxplot/multi1 (two named series)" do
      p = UnicodePlot.boxplot(
        ["one", "two"],
        [[1.0, 2.0, 3.0, 4.0, 5.0], [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]],
        title: "Multi-series", xlabel: "foo", color: :yellow
      )
      test_ref("boxplot/multi1.txt", p)
    end

    it "matches boxplot/multi2 (after boxplot! appends third series)" do
      p = UnicodePlot.boxplot(
        ["one", "two"],
        [[1.0, 2.0, 3.0, 4.0, 5.0], [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]],
        title: "Multi-series", xlabel: "foo", color: :yellow
      )
      UnicodePlot.boxplot!(p, "one more", [-1.0, 2.0, 3.0, 4.0, 11.0])
      test_ref("boxplot/multi2.txt", p)
    end

    it "matches boxplot/multi3 (after second boxplot! with name kwarg)" do
      p = UnicodePlot.boxplot(
        ["one", "two"],
        [[1.0, 2.0, 3.0, 4.0, 5.0], [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]],
        title: "Multi-series", xlabel: "foo", color: :yellow
      )
      UnicodePlot.boxplot!(p, "one more", [-1.0, 2.0, 3.0, 4.0, 11.0])
      UnicodePlot.boxplot!(p, [4.0, 2.0, 2.5, 4.0, 14.0], name: "last one")
      test_ref("boxplot/multi3.txt", p)
    end

    it "matches boxplot/multi4 (unnamed multi-series)" do
      p = UnicodePlot.boxplot([[1.0, 2.0, 3.0, 4.0, 5.0], [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]])
      test_ref("boxplot/multi4.txt", p)
    end
  end

  describe "heatmap" do
    # integers_20x20: repeat(collect(1:20), outer=(1,20)) → A[i,j] = i
    it "matches heatmap/integers_20x20" do
      z = Array.new(20) { |i| Array.new(20) { |_j| (i + 1).to_f } }
      p = UnicodePlot.heatmap(z)
      test_ref("heatmap/integers_20x20.txt", p)
    end

    # zeros_20x20: all zeros
    it "matches heatmap/zeros_20x20" do
      z = Array.new(20) { Array.new(20, 0.0) }
      p = UnicodePlot.heatmap(z)
      test_ref("heatmap/zeros_20x20.txt", p)
    end

    # fix_aspect_ratio_30x30: outer product 1:30 × 1:30, fix_ar=true
    it "matches heatmap/fix_aspect_ratio_30x30" do
      z = Array.new(30) { |i| Array.new(30) { |j| (i + 1).to_f * (j + 1).to_f } }
      p = UnicodePlot.heatmap(z, fix_ar: true)
      test_ref("heatmap/fix_aspect_ratio_30x30.txt", p)
    end

    # array_convention: outer product 1:20 × 1:20, array=true, fix_ar=true
    it "matches heatmap/array_convention" do
      z = Array.new(20) { |i| Array.new(20) { |j| (i + 1).to_f * (j + 1).to_f } }
      p = UnicodePlot.heatmap(z, array: true, fix_ar: true)
      test_ref("heatmap/array_convention.txt", p)
    end

    # scaling_11x11_xfact_0.1: repeat(collect(0:10), outer=(1,11)) → A[i,j] = i-1; xfact=0.1
    it "matches heatmap/scaling_11x11_xfact_0.1" do
      z = Array.new(11) { |i| Array.new(11) { |_j| i.to_f } }
      p = UnicodePlot.heatmap(z, xfact: 0.1)
      test_ref("heatmap/scaling_11x11_xfact_0.1.txt", p)
    end

    # scaling_11x11_yfact_0.1
    it "matches heatmap/scaling_11x11_yfact_0.1" do
      z = Array.new(11) { |i| Array.new(11) { |_j| i.to_f } }
      p = UnicodePlot.heatmap(z, yfact: 0.1)
      test_ref("heatmap/scaling_11x11_yfact_0.1.txt", p)
    end

    # scaling_11x11_xfact_0.1_xoffset_-0.5
    it "matches heatmap/scaling_11x11_xfact_0.1_xoffset_-0.5" do
      z = Array.new(11) { |i| Array.new(11) { |_j| i.to_f } }
      p = UnicodePlot.heatmap(z, xfact: 0.1, xoffset: -0.5)
      test_ref("heatmap/scaling_11x11_xfact_0.1_xoffset_-0.5.txt", p)
    end

    # scaling_11x11_yfact_0.1_yoffset_-0.5
    it "matches heatmap/scaling_11x11_yfact_0.1_yoffset_-0.5" do
      z = Array.new(11) { |i| Array.new(11) { |_j| i.to_f } }
      p = UnicodePlot.heatmap(z, yfact: 0.1, yoffset: -0.5)
      test_ref("heatmap/scaling_11x11_yfact_0.1_yoffset_-0.5.txt", p)
    end

    # scaling_11x11_xfact_0.1_xoffset_-0.5_yfact_10_yoffset_-50
    it "matches heatmap/scaling_11x11_xfact_0.1_xoffset_-0.5_yfact_10_yoffset_-50" do
      z = Array.new(11) { |i| Array.new(11) { |_j| i.to_f } }
      p = UnicodePlot.heatmap(z, xfact: 0.1, xoffset: -0.5, yfact: 10.0, yoffset: -50.0)
      test_ref("heatmap/scaling_11x11_xfact_0.1_xoffset_-0.5_yfact_10_yoffset_-50.txt", p)
    end

    # limits_31x31: outer product 0:30 × 0:30 → A[i,j] = (i-1)*(j-1) in Julia = i*j in Crystal (0-indexed)
    it "matches heatmap/limits_31x31_ylim_10_20" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, ylim: {10.0, 20.0})
      test_ref("heatmap/limits_31x31_ylim_10_20.txt", p)
    end

    it "matches heatmap/limits_31x31_xlim_10_20" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, xlim: {10.0, 20.0})
      test_ref("heatmap/limits_31x31_xlim_10_20.txt", p)
    end

    it "matches heatmap/limits_31x31_xlim_10_20_ylim_10_20" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, xlim: {10.0, 20.0}, ylim: {10.0, 20.0})
      test_ref("heatmap/limits_31x31_xlim_10_20_ylim_10_20.txt", p)
    end

    it "matches heatmap/limits_31x31_ylim_50_50" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, ylim: {50.0, 50.0})
      test_ref("heatmap/limits_31x31_ylim_50_50.txt", p)
    end

    it "matches heatmap/limits_31x31_zlim_0_1800" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, zlim: {0.0, 1800.0})
      test_ref("heatmap/limits_31x31_zlim_0_1800.txt", p)
    end

    it "matches heatmap/limits_31x31_ylim_1_50" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, ylim: {1.0, 50.0})
      test_ref("heatmap/limits_31x31_ylim_1_50.txt", p)
    end

    it "matches heatmap/limits_31x31_xlim_1_50" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, xlim: {1.0, 50.0})
      test_ref("heatmap/limits_31x31_xlim_1_50.txt", p)
    end

    it "matches heatmap/limits_31x31_xlim_1_50_ylim_1_50" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, xlim: {1.0, 50.0}, ylim: {1.0, 50.0})
      test_ref("heatmap/limits_31x31_xlim_1_50_ylim_1_50.txt", p)
    end

    it "matches heatmap/limits_31x31_xlim_50_60" do
      z = Array.new(31) { |i| Array.new(31) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, xlim: {50.0, 60.0})
      test_ref("heatmap/limits_31x31_xlim_50_60.txt", p)
    end

    it "matches heatmap/parameters_60x60_colorbar_false" do
      z = Array.new(60) { |i| Array.new(60) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, colorbar: false)
      test_ref("heatmap/parameters_60x60_colorbar_false.txt", p)
    end

    it "matches heatmap/parameters_60x60_labels_false" do
      z = Array.new(60) { |i| Array.new(60) { |j| i.to_f * j.to_f } }
      p = UnicodePlot.heatmap(z, labels: false)
      test_ref("heatmap/parameters_60x60_labels_false.txt", p)
    end

    it "matches heatmap/parameters_60x60_title_hmap_zlabel_lab_colorbar_border_ascii_colormap_inferno" do
      z = heatmap_fixture_matrix("60x60")
      p = UnicodePlot.heatmap(z,
        title: "hmap", zlabel: "lab",
        colorbar_border: :ascii, colormap: :inferno)
      test_ref("heatmap/parameters_60x60_title_hmap_zlabel_lab_colorbar_border_ascii_colormap_inferno.txt", p)
    end

    it "matches heatmap/parameters_10x10_xfact_0.1" do
      z = heatmap_fixture_matrix("10x10")
      p = UnicodePlot.heatmap(z, xfact: 0.1)
      test_ref("heatmap/parameters_10x10_xfact_0.1.txt", p)
    end

    it "matches heatmap/parameters_10x10_yfact_1" do
      z = heatmap_fixture_matrix("10x10")
      p = UnicodePlot.heatmap(z, yfact: 1.0)
      test_ref("heatmap/parameters_10x10_yfact_1.txt", p)
    end

    it "matches heatmap/parameters_10x11_xfact_0.1" do
      z = heatmap_fixture_matrix("10x11")
      p = UnicodePlot.heatmap(z, xfact: 0.1)
      test_ref("heatmap/parameters_10x11_xfact_0.1.txt", p)
    end

    it "matches heatmap/parameters_10x11_yfact_1" do
      z = heatmap_fixture_matrix("10x11")
      p = UnicodePlot.heatmap(z, yfact: 1.0)
      test_ref("heatmap/parameters_10x11_yfact_1.txt", p)
    end
  end

  describe "densityplot" do
    it "matches densityplot/densityplot" do
      x = DENSITYPLOT_X
      y = DENSITYPLOT_Y
      p = UnicodePlot.densityplot(x, y)
      UnicodePlot.densityplot!(p, x.map { |v| v + 2.0 }, y.map { |v| v + 2.0 })
      test_ref("densityplot/densityplot.txt", p)
    end

    it "matches densityplot/densityplot_parameters" do
      x = DENSITYPLOT_X
      y = DENSITYPLOT_Y
      p = UnicodePlot.densityplot(x, y, name: "foo", color: :red, title: "Title", xlabel: "x")
      UnicodePlot.densityplot!(p, x.map { |v| v + 2.0 }, y.map { |v| v + 2.0 }, name: "bar")
      test_ref("densityplot/densityplot_parameters.txt", p)
    end

    it "matches densityplot/densityplot_dscale_identity" do
      x = densityplot_fixture_xprime(DENSITYPLOT_X)
      p = UnicodePlot.densityplot(x, DENSITYPLOT_Y, dscale: :identity)
      test_ref("densityplot/densityplot_dscale_identity.txt", p)
    end

    it "matches densityplot/densityplot_dscale_sqrt" do
      x = densityplot_fixture_xprime(DENSITYPLOT_X)
      p = UnicodePlot.densityplot(x, DENSITYPLOT_Y, dscale: :sqrt)
      test_ref("densityplot/densityplot_dscale_sqrt.txt", p)
    end

    it "matches densityplot/densityplot_dscale_log" do
      x = densityplot_fixture_xprime(DENSITYPLOT_X)
      p = UnicodePlot.densityplot(x, DENSITYPLOT_Y, dscale: ->(v : Float64) { Math.log(1.0 + v) })
      test_ref("densityplot/densityplot_dscale_log.txt", p)
    end

    it "matches densityplot/densityplot_dscale_custom" do
      x = densityplot_fixture_xprime(DENSITYPLOT_X)
      p = UnicodePlot.densityplot(x, DENSITYPLOT_Y, dscale: ->(v : Float64) { v / (v + 1.0) })
      test_ref("densityplot/densityplot_dscale_custom.txt", p)
    end
  end
end
